require("core.configs")
require("core.mappings")
require("core.cmds")
require("core.lsp")
require("my.myfunc")
-- require("my.snippets").setup()
-- packs:
require('packs.gruvboxsi')
require('packs.mautopairs')
require('packs.mbuffers')
require('packs.malpha')
require('packs.snippets')
-- временно отключено
-- require('packs.nvim-treesitter')
-- require('packs.mason')
require('packs.diffview')
