require("core.configs")
require("core.mappings")
-- require("core.lazy")
require("core.cmds")
require("core.lsp")
require("my.myfunc")
-- require("my.malpha")
-- packs:
require('packs.gruvboxsi')
require('packs.mautopairs')
require('packs.mbuffers')
require('packs.treesitter')
require('packs.malpha')
-- временно отключен, включается для обновления lsp-servers
-- require('packs.mason')
